version: '3.9'

services:

  backend:
    build:
      context: ./backend
    container_name: smartmess_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - smartmess_network

  frontend:
    build:
      context: ./frontend
    container_name: smartmess_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - smartmess_network

  postgres:
    image: postgres:16-alpine
    container_name: smartmess_postgres

    environment:
      POSTGRES_DB: smartmess_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - smartmess_network

  nginx:
    image: nginx:latest
    container_name: smartmess_nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - frontend
      - backend

    networks:
      - smartmess_network

volumes:
  postgres_data:

networks:
  smartmess_network:
    driver: bridge