# Generated by Django 6.0.4 on 2026-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_messmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmenu',
            name='snacks',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RotatingMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('A', 'Week A'), ('B', 'Week B')], max_length=1)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('breakfast', models.TextField(blank=True)),
                ('lunch', models.TextField(blank=True)),
                ('snacks', models.TextField(blank=True)),
                ('dinner', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['week', 'day'],
                'unique_together': {('week', 'day')},
            },
        ),
    ]
